config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :albums do
    resources :photos, only: [:create, :destroy, :new]#, :update, :new, :edit]
  end
  resources :articles
  root 'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :schedules
  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord



extend FriendlyId
friendly_id :title, use: :slugged

mount_uploader :banner_image_url, ImageUploader 

has_many :taggings
has_many :tags, through: :taggings


def should_generate_new_friendly_id?
    title_changed?
end


def all_tags=(names)
  self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
  end
end

def all_tags
  self.tags.map(&:name).join(", ")
end

def self.tagged_with(name)
  Tag.find_by_name!(name).articles
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles  = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
   
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :slug, :banner_image_url, :all_tags)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def tag_links(tags)
  		tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end

	def tag_cloud(tags, classes)
  		max = tags.sort_by(&:count).last
 		tags.each do |tag|
  	  		index = tag.count.to_f / max.count * (classes.size-1)
    		yield(tag, classes[index.round])
  		end
	end
end

app/views/articles/_form.html.erb

<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
<div class="row">
<div class="form-inputs">
  <div class="col-sm-8">

     <li class="list-group-item">
        

        <div class="field">
          <%= f.input :title, class:'form-control' %>
        </div>

        <div class="field">
          <%= f.label :content %>
          <%= f.cktext_area :content, rows: 10, class:'form-control' %>
        </div>

        <div class="list-inline text-right">

        <button type="submit" class='btn btn-primary'>Simpan</button>

        <span onclick="window.location.href='/articles'" class='btn btn-danger'>Batal</span>
        <%=if !(defined?(menu)).nil?
              if menu ='edit'
                 link_to 'Tampilkan', article, class:'btn btn-success btn-a-white'
              end
          end %> 
    </li>
  </div>
  </div>


  <div class="col-sm-4">
    <li class="list-group-item">
    <div class="field">
        <%= f.label :all_tags %>
        <%= f.text_field :all_tags, placeholder: "Tags separated with comma", class:'form-control' %>
    </div>
    <div class="field">

          <%= f.label :banner_image_url %>
           <img class= "img-responsive" style="max-height: 150px" id="img_prev" src=<%=  @article.banner_image_url || "http://nemanjakovacevic.net/wp-content/uploads/2013/07/placeholder.png" %>  alt="your image" />
           <br/>
           <label class="btn btn-primary" for="image">Upload</label>
          <%= f.file_field :banner_image_url,id:"image", class:'form-control',  onchange:"readURL(this); $('#upload-file-info').html($(this).val());", style:"display:none;" %>
          <span class='label label-info' id="upload-file-info"></span>

    </div>
   </li>
    
  </div> 

</div>

  <!-- Assume jQuery is loaded -->
    <script>
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#img_prev')
              .attr('src', e.target.result)
          };

          reader.readAsDataURL(input.files[0]);
        }
      }
    </script>
  


  
    


  
<% end %>

app/views/articles/edit.html.erb
<%provide(:page_title, @article.title) %>
<h1>Edit Artikel</h1>

<%= render 'form', article: @article, menu: 'edit'%>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<%provide(:page_title, "Artikel") %>
<div class="row">
  <div class="col-sm-8">
    <h1>Daftar Artikel</h1>
  </div>
  <div class="col-sm-4 text-right">
    <%= link_to 'Buat Artikel Baru ', new_article_path, class:"btn btn-info btn-a-white " %>
  </div>
</div>


<div class="tags-cloud glassy-bg">
 <!--  <h4>Tags Cloud</h4>
 <% tag_cloud Tag.counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
   <%= link_to tag.name, tag_path(tag.name), class: css_class %>
 <% end %>
 </div> -->
 

<table class="table table-striped">
  <thead>
    <tr>
      <th>Judul</th>
      <th>Konten</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody  >
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>

        <td><%=  truncate(strip_tags(article.content) , length:30)%></td>
        <td><%=raw tag_links(article.all_tags)%></td>
        <td><%= link_to 'visibility' ,article, class:'btn btn-success material-icons btn-a-white' %></td>
        <td><%= link_to 'edit', edit_article_path(article),  class:'btn btn-primary material-icons btn-a-white' %></td>
        <td><%= link_to 'delete', article, method: :delete, data: { confirm: 'Are you sure?' },  class:'btn btn-danger material-icons btn-a-white' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/articles/new.html.erb
<%provide(:page_title, "Tambah Artikel") %>

<h1>Tambah Artikel</h1>

<%= render 'form', article: @article%>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%provide(:page_title, @article.title) %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content.html_safe %>
</p>



<%= link_to 'Edit', edit_article_path(@article), class:'btn btn-primary btn-a-white' %> |
<%= link_to 'Back', articles_path, class:'btn btn-danger btn-a-white material-icon' %>